# Generated by Django 3.2.9 on 2021-11-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma_tem_disciplina',
            name='status_agendamento',
            field=models.BooleanField(default=False),
        ),
    ]
