# Generated by Django 3.2.9 on 2021-11-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
