# Generated by Django 3.2.9 on 2021-11-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.FloatField(),
        ),
    ]
