# Generated by Django 3.2.9 on 2021-11-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_nota_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma_tem_disciplina',
            name='data_e_hora',
        ),
    ]
