# Generated by Django 3.2.9 on 2021-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_remove_turma_tem_disciplina_data_e_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.IntegerField(null=True),
        ),
    ]
